#!/bin/sh

cd server
    tsc-watch --noClear --onSuccess "npx vlquery compile" &
cd ..

cd client
    tsc-watch --noClear --onSuccess "npx vldom compile" &

    cd assets
        nodemon -e scss -x "sass styles.scss ../dist/styles.css" &
    cd ..
cd ..

cd server
    PGHOST=10.22.0.1 PGUSER=townhall PGPASSWORD=townhall PGDATABASE=townhall VLQUERY_LOG_SQL=TRUE TOWNHALL_SERVER_ADDRESS=http://10.22.0.1:8000/townhall nodemon dist/main.js
cd ..