#!/bin/sh

cd server
    tsc-watch --noClear --onSuccess "npx vlquery compile" &
cd ..

cd client
    tsc-watch --noClear --onSuccess "npx vldom compile" &

    cd assets
        nodemon -e scss -x "sass styles.scss ../dist/styles.css" &
    cd ..
cd ..

cd server
    PGHOST=data1.w6.cloud.acryps.com PGUSER=townhall PGPASSWORD=townhall PGDATABASE=townhall VLQUERY_LOG_SQL=TRUE nodemon dist/main.js
cd ..